use ::phf::{Map, phf_map};
use crate::egui::*;

pub static VIRTUAL_CODES: Map<char, Key> = phf_map! {
    '0'	=> Key::Num0,
    '1'	=> Key::Num1,
    '2' => Key::Num2,
    '3' => Key::Num3,
    '4' => Key::Num4,
    '5' => Key::Num5,
    '6' => Key::Num6,
    '7' => Key::Num7,
    '8' => Key::Num8,
    '9' => Key::Num9,
    'a' => Key::A,
    'b' => Key::B,
    'c' => Key::C,
    'd' => Key::D,
    'e' => Key::E,
    'f' => Key::F,
    'g' => Key::G,
    'h' => Key::H,
    'i' => Key::I,
    'j' => Key::J,
    'k' => Key::K,
    'l' => Key::L,
    'm' => Key::M,
    'n' => Key::N,
    'o' => Key::O,
    'p' => Key::P,
    'q' => Key::Q,
    'r' => Key::R,
    's' => Key::S,
    't' => Key::T,
    'u' => Key::U,
    'v' => Key::V,
    'w' => Key::W,
    'x' => Key::X,
    'y' => Key::Y,
    'z' => Key::Z,
    // ',' => b'\xbc' as i32,
    // '.' => b'\xbe' as i32,
    // '/' => b'\xbf' as i32,
};

/*
pub static VIRTUAL_CODES: Map<char, i32> = phf_map! {
    '0'	=> 0x30,
    '1'	=> 0x31,
    '2' => 0x32,
    '3' => 0x33,
    '4' => 0x34,
    '5' => 0x35,
    '6' => 0x36,
    '7' => 0x37,
    '8' => 0x38,
    '9' => 0x39,
    'a' => 0x41,
    'b' => 0x42,
    'c' => 0x43,
    'd' => 0x44,
    'e' => 0x45,
    'f' => 0x46,
    'g' => 0x47,
    'h' => 0x48,
    'i' => 0x49,
    'j' => 0x4A,
    'k' => 0x4B,
    'l' => 0x4C,
    'm' => 0x4D,
    'n' => 0x4E,
    'o' => 0x4F,
    'p' => 0x50,
    'q' => 0x51,
    'r' => 0x52,
    's' => 0x53,
    't' => 0x54,
    'u' => 0x55,
    'v' => 0x56,
    'w' => 0x57,
    'x' => 0x58,
    'y' => 0x59,
    'z' => 0x5A,
    ',' => b'\xbc' as i32,
    '.' => b'\xbe' as i32,
    '/' => b'\xbf' as i32,
};

 */