use egui::Key;
use ::phf::{Map, phf_map};

pub static VIRTUAL_CODES: Map<char, Key> = phf_map! {
    '0'	=> Key::Num0,
    '1'	=> Key::Num1,
    '2' => Key::Num2,
    '3' => Key::Num3,
    '4' => Key::Num4,
    '5' => Key::Num5,
    '6' => Key::Num6,
    '7' => Key::Num7,
    '8' => Key::Num8,
    '9' => Key::Num9,
    'a' => Key::A,
    'b' => Key::B,
    'c' => Key::C,
    'd' => Key::D,
    'e' => Key::E,
    'f' => Key::F,
    'g' => Key::G,
    'h' => Key::H,
    'i' => Key::I,
    'j' => Key::J,
    'k' => Key::K,
    'l' => Key::L,
    'm' => Key::M,
    'n' => Key::N,
    'o' => Key::O,
    'p' => Key::P,
    'q' => Key::Q,
    'r' => Key::R,
    's' => Key::S,
    't' => Key::T,
    'u' => Key::U,
    'v' => Key::V,
    'w' => Key::W,
    'x' => Key::X,
    'y' => Key::Y,
    'z' => Key::Z,
};
